version: '3'
services:
  iris:
    build: .

    ports:
      - "52773:52773"
      - "51773:51773"
    volumes:
      - "./:/home/project/shared/Samples-FHIR-Oximeter-Devices/"
    hostname: iris-sample
